# To run all pre-commit checks, use:
#
#     uvx prek run -a
#
# To install pre-commit hooks that run every time you commit:
#
#     uv tool install prek
#     prek install
#

ci:
  autoupdate_commit_msg: "⬆️🪝 update pre-commit hooks"
  autoupdate_schedule: quarterly
  autofix_commit_msg: "🎨 pre-commit fixes"
  skip: [swift-format, swift-format-lint]

repos:
  ## Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
        args: [--assume-in-merge]
        fail_fast: true
        priority: 0
      - id: end-of-file-fixer
        priority: 1
      - id: trailing-whitespace
        priority: 2

  ## Check JSON schemata
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.4
    hooks:
      - id: check-github-workflows
        priority: 0

  ## Format and lint Swift files with swift-format
  - repo: https://github.com/swiftlang/swift-format
    rev: 603.0.0
    hooks:
      - id: swift-format
        priority: 5
      - id: swift-format-lint
        priority: 6
